LOAD_WAYPOINTS = True  # True if training, False if pre-processing

PROCESS_SUBGOALS = False
PROCESS_GOALS = True
ENABLE_INTERVALS = True
VISUALIZE_DATASET = False
VISUALIZE_SUBGOALS = False
VISUALIZE_STL = False

RESET_IMG_DIR = True
RESET_LATENT_DIR = False

IMG_DIR = './images'
LATENT_DIR = './latents'

NUM_THRESH = 1
PERSISTENCE_THRESH = 10
SIM_THRESH = [0.1, 0.125]